src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Repository\ContactRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=ContactRepository::class)
 */
class Contact
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $first_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $last_name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $address;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $zip;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $city;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $country;

    /**
     * @ORM\Column(type="integer")
     */
    private $phone_number;

    /**
     * @ORM\Column(type="date")
     */
    private $birthday;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $picture;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): self
    {
        $this->first_name = $first_name;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): self
    {
        $this->last_name = $last_name;

        return $this;
    }

    public function getAddress(): ?string
    {
        return $this->address;
    }

    public function setAddress(string $address): self
    {
        $this->address = $address;

        return $this;
    }

    public function getZip(): ?string
    {
        return $this->zip;
    }

    public function setZip(string $zip): self
    {
        $this->zip = $zip;

        return $this;
    }

    public function getCity(): ?string
    {
        return $this->city;
    }

    public function setCity(string $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getCountry(): ?string
    {
        return $this->country;
    }

    public function setCountry(string $country): self
    {
        $this->country = $country;

        return $this;
    }

    public function getPhoneNumber(): ?int
    {
        return $this->phone_number;
    }

    public function setPhoneNumber(int $phone_number): self
    {
        $this->phone_number = $phone_number;

        return $this;
    }

    public function getBirthday(): ?\DateTimeInterface
    {
        return $this->birthday;
    }

    public function setBirthday(\DateTimeInterface $birthday): self
    {
        $this->birthday = $birthday;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }
}

src/Controller/ContactController.php
<?php

namespace App\Controller;

use App\Entity\Contact;
use App\Form\CreateContactType;
use App\Service\ContactService;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;


class ContactController extends AbstractController
{
    private $contactService;
    private $logger;

    public function __construct(ContactService $contactService, LoggerInterface $logger)
    {
        $this->contactService = $contactService;
        $this->logger = $logger;
    }

    /**
     * @Route("/contacts/index", name="app_contact_list")
     * @Route("/", name="index")
     */
    public function index(): Response
    {
        try {
            $contactList = $this->contactService->list();
            foreach ($contactList as $contact) {
                $contact->deleteForm = $this->createFormBuilder()
                    ->setAction($this->generateUrl('app_contact_delete', ['id' => $contact->id]))
                    ->setMethod(Request::METHOD_DELETE)
                    ->add('Delete', SubmitType::class)
                    ->getForm()->createView();
            }

        } catch (\Exception $exception) {
            $contactList = [];
            $this->logger->error($exception->getMessage());
            $this->addFlash('danger', $exception->getMessage());
        }

        return $this->render('contact/index.html.twig', [
            'contactList' => $contactList,
        ]);
    }

    /**
     * @Route("/contacts/createorupdate", name="app_contact_create")
     */
    public function create(Request $request): Response
    {
        $id = $request->get('id');
        if ($id) {
            $contact = $this->contactService->getRowById($id);
            if (!$contact) {
                $this->addFlash('danger', 'Unable to find contact');
                return $this->redirectToRoute('app_contact_list');
            }
        } else {
            $contact = new Contact();
        }

        try {
            $form = $this->createForm(CreateContactType::class, $contact);
            $form->handleRequest($request);
            if ($form->isSubmitted() && $form->isValid()) {
                $this->contactService->saveOrUpdate($form);
                $this->addFlash('success', 'Contact saved');
                return $this->redirectToRoute('app_contact_list');
            }
        } catch (\Exception $exception) {
            $this->logger->error($exception->getMessage());
            $this->addFlash('danger', $exception->getMessage());
        }


        return $this->renderForm('contact/create.html.twig', [
            'form' => $form,
        ]);
    }

    /**
     * @Route("/contacts/delete", name="app_contact_delete")
     */
    public function delete(Request $request, int $id): Response
    {
        if ($request->get('_method') !== Request::METHOD_DELETE) {
            $this->addFlash('danger', 'Invalid request-type');
            return $this->redirectToRoute('app_contact_list');
        }
        try {
            $isDeleted = $this->contactService->delete($id);
            if ($isDeleted) {
                $this->addFlash('success', 'Contact deleted.');
            } else {
                $this->addFlash('danger', 'Contact not found.');
            }
        } catch (\Exception $exception) {
            $this->logger->error($exception->getMessage());
            $this->addFlash('danger', $exception->getMessage());
        }
        return $this->redirectToRoute('app_contact_list');
    }

}

templates/contact/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add-Edit Contact!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    {{ form(form) }}

</div>
{% endblock %}

templates/contact/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Manage Contact!{% endblock %}

{% block body %}
    <div class="example-wrapper">

        <div class="row">
            <div class="col-md-8 clearfix">
                <h1>Manage Contacts</h1>
            </div>
            <div class="col-md-4 text-right pt-2">
                <a class="btn btn-primary " href="{{ path('app_contact_create') }}">Add New</a>
            </div>
        </div>
        <div class="row">
            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{ label }}">
                        {{ message|trans }}
                    </div>
                {% endfor %}
            {% endfor %}
        </div>

        <div class="row">
            <table class="table">
                <thead>
                <tr>
                    <th>First Name</th>
                    <th>Last Name</th>
                    <th>Phone number</th>
                    <th>Birthday</th>
                    <th>Picture</th>
                    <th>Actions</th>
                </tr>
                </thead>
                <tbody>
                {% for contact in contactList %}
                    <tr>
                        <td>{{ contact.firstName }}</td>
                        <td>{{ contact.lastName }}</td>
                        <td>{{ contact.phoneNumber }}</td>
                        <td>{{ contact.birthday }}</td>
                        <td class="col-2"><img src="{{ asset(contact.picture) }}" class="w-50" ></td>
                        <td>
                            <a href="{{ path('app_contact_create', { 'id' : contact.id }) }}">Edit</a> | {{ form(contact.deleteForm) }}
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
{% endblock %}